### ISSUE TITLE
Import/export layouts

### ISSUE THREAD

**Issue by tomalec** [StarcounterAppsFreezer/Launcher#222]
@malx122 Requested a feature to import/export layouts for all partials, preferably by a button in the editor + automation tool.

I think automation tool could come from Starcounter CLI migration, as layouts are now stored in `Starcounter.Launcher`.

My doubt is whether we would like to put yet another control into editor that already suffers featuritis.
Maybe we can add it to Launcher's settings?

**Comment by tomalec** [comment]
note: we already have something written at https://github.com/StarcounterPrefabs/Launcher/wiki/How-to-save-and-restore-layouts-(database-dump) but it's probably totally out of date.

**Comment by malx122** [comment]
It actually only tells how to dump a WHOLE db and reload it in to a empty one. Nothing about import/export just the layouts.

**Comment by malx122** [comment]
What is the status of this?

**Comment by tomalec** [comment]
@miyconst, @andwah  Do you think we can implement such thing in administrator?
This is f the last things blocking Tunity from adopting the new Shadow DOM layouts

**Comment by tomalec** [comment]
//related https://github.com/Starcounter/Starcounter/issues/2833

**Comment by miyconst** [comment]
Some time ago it was agreed to add the Database Editor app into the administrator. The app should have import/export tools. 

I don't think it's a good idea to add this particular feature to the administrator itself.

**Comment by tomalec** [comment]
As far as I understood they need some kind of deployment tool.

@malx122, could you take a look at Database Editor and check if "export" button at http://localhost:8080/databaseeditor/tables/Starcounter.Layout is more or less what you need?

@miyconst, Is it finished? I get an error
```
excel:1 Uncaught SyntaxError: Unexpected token P in JSON at position 0
```
when trying to export layouts.

**Comment by warpech** [comment]
Allegedly, it should be possible now to do an export and import of HTMLCompositions using `stardump` instead of the current ways (REST API and creating `new HTMLComposition()` in code).

@un-tone can you check if that is a feasible alternative?

**Comment by un-tone** [comment]
There is an issue with `reload` operation. I tested in 2.3.0.6385 version.

I successfully unloaded the data with the following command:
```
StarDump.exe unload --database default --file C:\Backup\Starcounter\inside-html-compositions.sqlite3 --unloadtables Starcounter.HTMLComposition
```

Then the following command throws an exception:
```
StarDump.exe reload --database default --file C:\Backup\Starcounter\inside-html-compositions.sqlite3 --reassignobjectno --forcereload
```
The output:
```
Reload started C:\Backup\Starcounter\inside-html-compositions.sqlite3
Warnings (248), make sure to take care of object ID uniqueness and table schemas:
  Database is not empty: Table Simplified.Ring1.Something already exists.
...
...
  Database is not empty: Table Chatter.SavedSession already exists.                                                                                                                                  
                                                                                                                                                                                                     
                                                                                                                                                                                                     
Usage:  reload [options]                                                                                                                                                                             
                                                                                                                                                                                                     
Options:                                                                                                                                                                                             
  -db | --database <DatabaseName>   Name of starcounter database to dump.                                                                                                                            
  -f | --file <FullFileName>        Full name to dump file.                                                                                                                                          
  -fr | --forcereload               Force reload even if the database already contains data. User has to take care of object ID uniqueness.                                                          
  -offset | --insertobjectnooffset  ObjectNo offset in the target database. Useful when combining data of multiple databases.                                                                        
  -reassign | --reassignobjectno    Sets ObjectNo offset to the maximum used number in the target database.                                                                                          
  -? | -h | --help                  Show help information                                                                                                                                            
                                                                                                                                                                                                     
Starcounter.Core.StarcounterException: SCERR15009 Schema of the input type does not match schema of existing type:                                                                                   
 Starcounter.HTMLComposition with input columns:                                                                                                                                                     
Version,Key                                                                                                                                                                                          
   at Starcounter.Core.Db.MetalayerCheck(UInt32 r)                                                                                                                                                   
   at StarDump.Core.Reload.CreateTable(ReloadTable table, List`1 columns) in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\Reload.cs:line 255                                       
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<CreateTable>b__0() in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\Reload.cs:line 241                                            
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)                                                                                                                          
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)                                                                                                             
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)                                                                                                                           
   at StarDump.Core.Reload.CreateTables(SqliteConnection cn, List`1 tables) in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\Reload.cs:line 208                                     
   at StarDump.Core.Reload.CreateTablesAndInsertData(SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\Reload.cs:line 191
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\Reload.cs:line 78                                                                                 
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump.Core\CommandInterface.cs:line 45                       
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-5049\StarDump\src\StarDump\CommandLineInterface.cs:line 208                      
```

I tried the same `reload` command in 2.3.0.6350 without `--reassignobjectno` parameter and got the same error.

Unloaded dump:
![image](https://cloud.githubusercontent.com/assets/1625378/25478921/ab4d4fda-2b4b-11e7-8e5e-fc0209058b72.png)

**Comment by warpech** [comment]
@miyconst could you pls help?

**Comment by Mackiovello** [comment]
Have we made any progress on this?

**Comment by Mackiovello** [comment]
I tried to recreate the steps by @un-tone. Got stuck when trying to unload:

```
C:\Program Files\Starcounter\StarDump>StarDump.exe unload --database default --file C:\Users\Erlend\dump.sqlite3 --unloadtables Starcounter.HTMLComposition
Unload started C:\Users\Erlend\dump.sqlite3


Usage:  unload [options]

Options:
  -db | --database <DatabaseName>               Name of starcounter database to dump
  -f | --file <FileName>                        Output dump filename
  -b | --buffersize <BufferSize>                Set insert rows buffer size to dump database.
  -scp | --skipcolumnprefixes <ColumnPrefixes>  Column prefixes to skip, space and/or comma separated. Example: -scp="a b,c"
  -stp | --skiptableprefixes <TablePrefixes>    Table prefixes to skip, space and/or comma separated. Example: -stp="a b,c"
  -st | --skiptables <TableNames>               Table names to skip, space and/or comma separated. Example: -stp="a b,c"
  -ut | --unloadtables <TableNames>             Table names to unlaod, space and/or comma separated. Example: -stp="a b,c"
  -? | -h | --help                              Show help information

Starcounter.Core.ScErrObjectNotAType: ScErrObjectNotAType (SCERR4019): Instantiation of a object failed because the object wasn't a registered type. TypeId=292
   at Starcounter.Core.Db.FromIdRef(UInt64 dbId, UInt64 dbRef)
   at Starcounter.Core.Database.SQLEnumerator`1.GetCurrentGeneric(SQLEnumerator`1 enumerator)
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-5591\StarDump\src\StarDump.Core\Unload.cs:line 88
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-5591\StarDump\src\StarDump.Core\Unload.cs:line 132
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-5591\StarDump\src\StarDump.Core\CommandInterface.cs:line 76
   at StarDump.CommandLineInterface.<>c__DisplayClass8_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-5591\StarDump\src\StarDump\CommandLineInterface.cs:line 135
```

@miyconst what am I doing wrong?

**Comment by Mackiovello** [comment]
This is needed to wrap up the remaining things for 2.3 https://github.com/Starcounter/RebelsLounge/issues/61

Solves https://github.com/Starcounter/level1/issues/3920

**Comment by warpech** [comment]
This is now tracked in https://github.com/Starcounter/RebelsLounge/issues/184
